### ISSUE TITLE
investigate how to implement push registration 

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/MYQuizClient#1]
- can we use a unified push API? 
- If not, how do we cover each platform?

**Comment by xyleninja** [comment]
found something we could use.
- [https://github.com/rdelrosario/xamarin-plugins/tree/master/PushNotification](url)

-> tech Proto in Progress.

issues: 
- it doesn't support Windows Phone.

personal issues: 
- can't use Mac Emulation. 
- IntelliSense doesn't work atm for me :(

Trying to get Droid done and share the techProto to test on mac devices.

**Comment by xyleninja** [comment]
Push Registration is working on Droid and UWP.
Need confirmation that it works on iOS aswell.

**Comment by TitanNano** [comment]
@xyleninja thats ok for now. I will investigate that later. please create a PR.
