### ISSUE TITLE
create mokups for each view 

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/MYQuizClient#2]
Please create a mokup for each view of the application. Post them for a last review and then put them into the wiki.

**Comment by ai-mt** [comment]
Please send me your feedback for the GUI concept. Thanks!
![guikonzept_neu](https://cloud.githubusercontent.com/assets/15248915/21957070/37c5b8d4-da8f-11e6-970d-3e42baf030fc.png)

**Comment by TitanNano** [comment]
@ai-mt 
- supervisor views go into a new repository. I will create one tomorrow or monday. 
- Id like to propose a slightly new concept:
   - the main view is a list of unanswered questions
   - if the user never joined a group we offer a button in the middle of this main view to give a quick access for adding the first group
   - the toolbar on the main view holds a add / plus button to access the modal "add a group" view, you called it "login" at them moment
   - on the right the toolbar offers a configuration button to open the group configuration view
   - the "add a group" view is basically your login view
   - the group configuration view shows a list with all groups a device is registered in. taping a list item lets the user leave the group. (please add a confirmation dialog) 
  - choosing a question from the main view, brings the user to the question view
- remove the type label from the question view, we don't have these types anymore, all questions are anonym.
- the question view needs multiple pages since we have the possibility of question lists. Please add an indicator for which question of a question list is displayed at the moment. 
- for your next draft please try to split up the views into separate images.

**Comment by ai-mt** [comment]
Every suggestion is integrated  in the new version except:

- the group configuration view shows a list with all groups a device is registered in. taping a list item lets the user leave the group. (please add a confirmation dialog)

Reasons:
- the user can only access/view 1 group and not all groups, in which he is registered 
- Adding/Deleting a user/group is done with the desktop App anyway

**Comment by ai-mt** [comment]
Here is the new GUI concept for the USER. Please send your Feedback. Thanks!


![guikonzept_user_v1 1](https://cloud.githubusercontent.com/assets/15248915/21981578/6eb7d4da-dbe8-11e6-864f-feaa87312333.png)

**Comment by ai-mt** [comment]
Here is the new GUI concept for the ADMIN. Please send your Feedback. Thanks!



![guikonzept_admin_v1 1](https://cloud.githubusercontent.com/assets/15248915/21981616/9b25d76a-dbe8-11e6-898c-d180018d9603.png)

**Comment by TitanNano** [comment]
For the UX concept:

- we need the ability to leave groups since we don't want to force users to stay in a group.
- logout button is obsolete, we don't need it.
- we still don't have a main view with all the open questions and available results, we need it because:
   - users might receive multiple questions at the same time
   - the supervisor might wants to publish the results of a question to the users

EDIT:
Please also make the progress a little bit more subtile and move it to the bottom.

**Comment by TitanNano** [comment]
this are the official requirements:
https://docs.google.com/document/d/19U4BFouusG2KD4sw1xqXqqgzz9HbjMKs6Mt7xT3eRDc/edit

**Comment by ai-mt** [comment]
I am sorry, I didn't know there were new requirements. Thanks for your hint.

So, next round for feedback is open :)

**Comment by ai-mt** [comment]
![guikonzept_user_v2 1](https://cloud.githubusercontent.com/assets/15248915/21999821/3ff1d8a4-dc3c-11e6-944a-47e007c145ae.png)

**Comment by ai-mt** [comment]
![guikonzept_admin_v2 0](https://cloud.githubusercontent.com/assets/15248915/21997660/bfff218e-dc30-11e6-96c1-46f285ea2384.png)

**Comment by TitanNano** [comment]
@ai-mt I moved the supervisor draft to a new repository. Please accept the invitation.

**Comment by ai-mt** [comment]
Here is the GUI for the users
![guikonzept_user_v4 0](https://cloud.githubusercontent.com/assets/15248915/22100047/242b15ce-de2e-11e6-92f8-4e5a7f125646.png)

**Comment by TitanNano** [comment]
@ai-mt when building the carousel view later on, please refer to this:
https://blog.xamarin.com/flip-through-items-with-xamarin-forms-carouselview/

**Comment by ai-mt** [comment]
new login page

![guikonzept_user_login](https://cloud.githubusercontent.com/assets/15248915/22102136/9fa03c68-de36-11e6-8f25-451a98c221eb.png)

**Comment by TitanNano** [comment]
okay great. please start with the first view.

**Comment by ai-mt** [comment]
![guikonzept_user_v4 2](https://cloud.githubusercontent.com/assets/15248915/22108784/0fb2941a-de55-11e6-945c-f405a8368392.png)

**Comment by TitanNano** [comment]
**Mobile Client**

- Maske Fragenseite
    - Gruppenname nicht anzeigen
    - Fragebogenname ganz oben anzeigen
    - Bei einer Frage nur “Frage” anzeigen

**Comment by ai-mt** [comment]
![guikonzept_user_fragenseite](https://cloud.githubusercontent.com/assets/15248915/22122163/2dfddbaa-de87-11e6-8955-f1234b7229e5.png)

**Comment by ai-mt** [comment]
**Letzte freigegebene GUI-Version für User:**

![guikonzept_user_v4 3](https://cloud.githubusercontent.com/assets/15248915/22221319/c52c0b04-e1b2-11e6-9267-91eac4b43b42.png)
